// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.6.1
// source: streamVod/streamVodpb/streamVod.proto

package streamVodpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoStreamServiceClient is the client API for VideoStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoStreamServiceClient interface {
	// client stream
	ImageFrame(ctx context.Context, opts ...grpc.CallOption) (VideoStreamService_ImageFrameClient, error)
}

type videoStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoStreamServiceClient(cc grpc.ClientConnInterface) VideoStreamServiceClient {
	return &videoStreamServiceClient{cc}
}

func (c *videoStreamServiceClient) ImageFrame(ctx context.Context, opts ...grpc.CallOption) (VideoStreamService_ImageFrameClient, error) {
	stream, err := c.cc.NewStream(ctx, &VideoStreamService_ServiceDesc.Streams[0], "/streamVod.videoStreamService/ImageFrame", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoStreamServiceImageFrameClient{stream}
	return x, nil
}

type VideoStreamService_ImageFrameClient interface {
	Send(*ImageFrameRequest) error
	CloseAndRecv() (*ImageFrameResponse, error)
	grpc.ClientStream
}

type videoStreamServiceImageFrameClient struct {
	grpc.ClientStream
}

func (x *videoStreamServiceImageFrameClient) Send(m *ImageFrameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *videoStreamServiceImageFrameClient) CloseAndRecv() (*ImageFrameResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImageFrameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoStreamServiceServer is the server API for VideoStreamService service.
// All implementations must embed UnimplementedVideoStreamServiceServer
// for forward compatibility
type VideoStreamServiceServer interface {
	// client stream
	ImageFrame(VideoStreamService_ImageFrameServer) error
	mustEmbedUnimplementedVideoStreamServiceServer()
}

// UnimplementedVideoStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoStreamServiceServer struct {
}

func (UnimplementedVideoStreamServiceServer) ImageFrame(VideoStreamService_ImageFrameServer) error {
	return status.Errorf(codes.Unimplemented, "method ImageFrame not implemented")
}
func (UnimplementedVideoStreamServiceServer) mustEmbedUnimplementedVideoStreamServiceServer() {}

// UnsafeVideoStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoStreamServiceServer will
// result in compilation errors.
type UnsafeVideoStreamServiceServer interface {
	mustEmbedUnimplementedVideoStreamServiceServer()
}

func RegisterVideoStreamServiceServer(s grpc.ServiceRegistrar, srv VideoStreamServiceServer) {
	s.RegisterService(&VideoStreamService_ServiceDesc, srv)
}

func _VideoStreamService_ImageFrame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoStreamServiceServer).ImageFrame(&videoStreamServiceImageFrameServer{stream})
}

type VideoStreamService_ImageFrameServer interface {
	SendAndClose(*ImageFrameResponse) error
	Recv() (*ImageFrameRequest, error)
	grpc.ServerStream
}

type videoStreamServiceImageFrameServer struct {
	grpc.ServerStream
}

func (x *videoStreamServiceImageFrameServer) SendAndClose(m *ImageFrameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *videoStreamServiceImageFrameServer) Recv() (*ImageFrameRequest, error) {
	m := new(ImageFrameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoStreamService_ServiceDesc is the grpc.ServiceDesc for VideoStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamVod.videoStreamService",
	HandlerType: (*VideoStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImageFrame",
			Handler:       _VideoStreamService_ImageFrame_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "streamVod/streamVodpb/streamVod.proto",
}
